// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:todo_app/storage/dto/task_dto.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'task_list_dto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'task_list_dto.g.dart';

@freezed
class TaskListDto with _$TaskListDto {
  const factory TaskListDto({
    required List<TaskDto> list,
    required int revision,
  }) = _TaskListDto;

  factory TaskListDto.fromJson(Map<String, Object?> json) =>
      _$TaskListDtoFromJson(json);
}
